region = "us-east-1"
name = "ameyrupji"
domain = "ameyrupji.com"
lambda-version = "v1.0.0"

main-subdomain = ""
alternate-subdomain = "www"
api-subdomain = "api"
code-subdomain = "code"
blog-subdomain = "blog"
images-subdomain = "images"
