region = "us-east-1"
name = "ameyrupji"
domain = "ameyrupji.com"
lambda-version = "v1.0.0"

main-subdomain = "beta"
alternate-subdomain = "www-beta"
api-subdomain = "api-beta"
code-subdomain = "code-beta"
blog-subdomain = "blog-beta"
images-subdomain = "images-beta"